### ISSUE TITLE
Request: HDR Shaders for Reshade 3.0

### ISSUE THREAD

**Issue by J1Man** [Heathen/Pirate-Shaders#1]
Please add HDR (High Dynamic Range) shaders to your collection if you can.  

The comments section of the HDR shader source files that are included in Reshade 3.0 says that they only simulate HDR look but are not real HDR shaders.  I am sure that you can make much higher quality and accurate HDR shaders.

I listed some reference websites below from Unity engine's website.  They explain how Unity engine combines HDR, Bloom, glow, tone mapping, ambient light and reflections to achieve best HDR pictures.  Sadly there are no formulas on these websites.  Just conceptual information.

https://unity3d.com/learn/tutorials/topics/graphics/introduction-lighting-and-rendering
https://docs.unity3d.com/Manual/HDR.html

Thanks for all your work.

**Comment by Heathen** [comment]
That's because reshade can only simulate it. The entire game engine has to be made to run in HDR for you to get proper HDR results. And even if it is, reshade only seems to get the render frame in 8 bits per channel, so whatever HDR there was, it was already converted to screen ranges.

**Comment by J1Man** [comment]
Thanks for the explanation and the quick reply.  In that case, please consider writing a Simulated HDR Shader when you have time.

**Comment by Heathen** [comment]
Light adaptation is the closest you can get to that without having to run every shader inside the same shader file in HDR then converting it back to 8bit.
