### ISSUE TITLE
Bug: Pirate SSAO shaders cause some artifacts in Star Wars Episode 1 Racer game.

### ISSUE THREAD

**Issue by J1Man** [Heathen/Pirate-Shaders#2]
Pirate SSAO shaders cause some artifacts in Star Wars Episode 1 Racer game.  Screenshots are included in the attached zip file (linked below).  SSAO Artifacts look like light sources behind frosted glass.

[Pirate Shaders -SSAO Bug Screenshots Star Wars Racer - Copy.zip](https://github.com/Heathen/Pirate-Shaders/files/661511/Pirate.Shaders.-SSAO.Bug.Screenshots.Star.Wars.Racer.-.Copy.zip)

Please note that this is an old game that I am running by using dgVoodoo2 v2.53 + reshade 3.0.5 + Pirate Shaders (master branch dated December 11, 2016). dgVoodoo2 is a wrapper that converts the game to DX11.  In the screenshots I only enabled Pirate_Depth_Preprocess and Pirate_Depth_SSAO.  Please let me know if this bug is fixable or not.

On a separate note, rest of the Pirate Shaders work without any problems/artifacts in this game.

**Comment by Heathen** [comment]
Turn off the scatter option on the SSAO config. It seems the depth buffer might not be configured right anyway.

Next version wont have scatter included in SSAO, plus I will make a small tutorial on how to properly set depth & AO

**Comment by J1Man** [comment]
Okay, I will wait for the next SSAO version and the tutorial.


This will be off topic, but there is an open-source project that I want to bring to your attention where your graphics shader skills can be very useful.  There is an open-source game engine remake project called OpenMW (Open Morrowind) on github (links below).  The engine is very close to 100% compatibility with Morrowind and will eventually add support for Oblivion, Skyrim and Skyrim SE.  Their goal is to improve the look of these games as much as possible on modern hardware.  OpenMW engine uses OpenSceneGraph for OpenGL rendering.

I think OpenMW project will benefit greatly if you port your shaders into their engine. They still don't have SSAO or other advanced shaders in their engine.  Their team members have very positive attitude regarding new code submissions and constantly say on the forums that they won't turn down any improvement opportunities.  Please keep OpenMW project in mind if you have free time in the future.

https://github.com/OpenMW/openmw
https://openmw.org/en/

**Comment by Heathen** [comment]
It's more of an issue of time. but they're free to use these shaders however they please.
